/*++

Copyright (c)  1999 - 2002 Intel Corporation. All rights reserved
This software and associated documentation (if any) is furnished
under a license and may only be used or copied in accordance
with the terms of the license. Except as permitted by such
license, no part of this software or documentation may be
reproduced, stored in a retrieval system, or transmitted in any
form or by any means without the express written consent of
Intel Corporation.


Module Name:
  
  buildNbr.h

Abstract:


Revision History

--*/
//this file generated by: updateBuildNbr.exe. version number format is: yyyymmddnn
#define BIS_CURRENT_VERSION_MINOR      2001013001
#define BIS_CURRENT_VERSION_MINOR_STR "2001013001"
